### ISSUE TITLE
Formik example

### ISSUE THREAD

**Issue by EvanBacon** [expo/examples#113]
**Describe the example you'd like**

Basic example of universal forms with https://jaredpalmer.com/formik

**Comment by amandeepmittal** [comment]
Hi @EvanBacon can I help with this example? Let me know what are you looking in a basic example? Would a small/single page form screen with Formik + yup is okay?

**Comment by byCedric** [comment]
I think that's a great start with the example 😄

**Comment by amandeepmittal** [comment]
Thanks @byCedric, let me get back with the example.
