### ISSUE TITLE
Does the script support image rotation prior to uploading images to firebase storage?

### ISSUE THREAD

**Issue by inglesuniversal** [expo/examples#138]
main because of iPhone exif data (6) forcing image to appear sideways on most browsers.

Thanks

**Comment by EvanBacon** [comment]
You can rotate an image using https://docs.expo.io/versions/latest/sdk/imagemanipulator/

**Comment by inglesuniversal** [comment]
@EvanBacon you are an Amazing Developer and Friend! STAY SAFE!
