### ISSUE TITLE
Remove yarn.lock from with-storybook

### ISSUE THREAD

**Issue by EvanBacon** [expo/examples#181]
- Lock package.json version to the latest versions that work as expected - requires manually testing
- Delete yarn.lock file to prevent dependabot issues

**Comment by YassineElbouchaibi** [comment]
Hey what is currently not working as expected, everything except the font story was working as expected for me. I was even able to upgrade to the latest @storybook/react-native version. For the font story, I was getting `Hooks can only be called inside the body of a function component.` until I did a small change. Ill open a PR.
