### ISSUE TITLE
Why does `with-redux` have an (out of date) Yarn lockfile?

### ISSUE THREAD

**Issue by Asday** [expo/examples#19]
https://github.com/expo/examples/tree/master/with-redux shows `package*.json` updated 9 days ago, but `yarn.lock` updated 9 _months_ ago.

I'm no expert, so I would love to know that I'm wrong in thinking that it should be deleted, 'cause that means I get to learn something.

**Comment by cruzach** [comment]
Thanks for pointing that out @Asday!

I updated it based off of the new `package-lock.json` 👍

**Comment by Asday** [comment]
Always a pleasure.
