### ISSUE TITLE
with-facebook-auth example not working on Android emulator

### ISSUE THREAD

**Issue by jonsmirl** [expo/examples#194]
**Describe the bug**
with-facebook-auth works for me on web.
On Android emulator it is failing with "No redirect URI in the params: No redirect present in the URI"

That error is because I don't have the redirect URI whitelisted. But what is the redirect URI I need to white list? The instructions tell me to check the logs for it. The URI is not displayed in the logs on Android.

I also see this error which may be related:
Linking requires that you provide a `scheme` in app.json for standalone apps 

Does the example need app.json to work on Android?

**To Reproduce**
Run the app on Android emulator, click the login button

**Expected behavior**
Should be able to login

Edit: found the URI, it is in Android logs, not Metro logs.
I added URI on FB developer console, but I still get same error.

This article is allowing me to get past the errors in the example app...
https://derk-jan.com/2020/05/expo-facebook-login/

**Comment by shawwal** [comment]
Hi You have to use "facebookAppId" and "facebookSecret" and set it up on your facebook apps developer account and add this: **Valid OAuth Redirect URIs** example:  https://auth.expo.io/@your-username/your-app-slug at this url: https://developers.facebook.com/apps/your-app-id/fb-login/settings/. You can read more details about it here. https://docs.expo.io/versions/latest/sdk/auth-session/. Here is the example of the app that integrate it properly: https://github.com/hyochan/Hygiene
