### ISSUE TITLE
Correct Redirect url

### ISSUE THREAD

**Issue by RyszardRzepa** [expo/examples#2]
Hey Brent!

I am having issues with the redirect url.
I am using google cloud functions to make a redirect url.

After success login, I am redirected to the enpoint where I am getting "Error: Not-Found".

I am curious if the is becouse of my redirect url to expo host?
I am not sure if it is the right format. 

I am colling the url like that` 'const RedirectURI = 'https://us-central1-coffee-cloud-mobile-app.cloudfunctions.net/facebookRedirect/facebook';'`

my cloud function:
```
const app = require('express')();
const cors = require("cors")

app.use(cors({ origin: true }))

app.get('/redirect', (req, res) => {
  let qs = req._parsedUrl.query;
  res.redirect('exp://exp.host/@ryszardrzpa/coffeecloud/+redirect/?' + qs);
});

app.get('/facebook', (req, res) => {
  res.sendFile('facebook.html', { root: __dirname });
});

module.exports = app;
```

Also if the app is build as stand alone app and push to the app store, will [exp://exp.host/@ryszardrzpa/coffeecloud](url)
 be valid redirect url?

Thanks,
Ryszard

**Comment by dikaiosune** [comment]
Hi! Is this in reference to the `with-facebook-auth` example? I just merged a big update from Brent and it might be worth taking another look.
