### ISSUE TITLE
Redirect Not working when handled from within a script handler

### ISSUE THREAD

**Issue by karanmartian** [expo/examples#21]
Hi,

This backend code for automatic redirection works well when this is the only html page used. However if I have redirected to this page from another page then the automatic redirection doesnt work. However manually clicking on the a href links back to the app still works. Have observed this on Android.

 Need some urgent help with this. Any thoughts?

**Comment by karanmartian** [comment]
I am pasting below my code, I have marked the location where this fails, basically I am trying to redirect from a handler of payment gateway code, but redirection doesn't work here. 

`<html>
    <head>
        <title>Redirect example</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <button id="rzp-button1">Pay</button>
        <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
        <script>
            var options = {
                key: "rzp_test_3olgIRtMqg69aE",
                amount: "19900", /// The amount is shown in currency subunits. Actual amount is ₹599.
                name: "Merchant Name",
                // "order_id": "<YOUR_ORDER_ID>", // Pass the order ID if you are using Razorpay Orders.
                currency: "INR", // Optional. Same as the Order currency
                description: "Purchase Description",
                image: "/your_logo.png",
                handler: function(response) {
                    // alert(response.razorpay_payment_id);
                    var qs = decodeURIComponent(document.location.search);
                    if (qs) {
                        baseUri = qs.split("?linkingUri=")[1];
                    }

                    alert(
                        baseUri +
                            "message=" +
                            encodeURIComponent(
                                "Redirected automatically by timer"
                            )
                    );
                    console.log(
                        baseUri +
                            "message=" +
                            encodeURIComponent(
                                "Redirected automatically by timer"
                            )
                    );

**////////////////////////////////// THIS FAILS //////////////////////////////////////**
                    window.location.href =
                        baseUri +
                        "message=" +
                        encodeURIComponent("Redirected automatically by timer");
                },
                prefill: {
                    name: "Gaurav Kumar",
                    email: "test@test.com"
                },
                notes: {
                    address: "Hello World"
                },
                theme: {
                    color: "#F37254"
                }
            };
            var rzp1 = new Razorpay(options);

            document.getElementById("rzp-button1").onclick = function(e) {
                rzp1.open();
                e.preventDefault();
            };
        </script>

        <script>
            document.addEventListener("DOMContentLoaded", function(event) {
                var links = document.querySelectorAll("a");
                var baseUri = "exp://wg-qka.notbrent.app.exp.direct";
                // Take the uri from the params
                var qs = decodeURIComponent(document.location.search);
                if (qs) {
                    baseUri = qs.split("?linkingUri=")[1];
                }
                // Update the link urls
                for (var i = 0; i < links.length; ++i) {
                    links[i].href = links[i].href.replace(
                        "exp://REPLACE_ME/",
                        baseUri
                    );
                    console.log(links[i].href);
                }

                var redirectInterval = setInterval(function() {
                    var countdown = document.querySelector(".countdown");
                    var t = parseInt(countdown.innerText, 10);
                    t -= 1;
                    countdown.innerText = t;
                    if (t === 0) {
                        clearInterval(redirectInterval);
                        window.location.href =
                            baseUri +
                            "message=" +
                            encodeURIComponent(
                                "Redirected automatically by timer"
                            );
                    }
                }, 1000);
            });
        </script>
    </head>

    <body>
        <h2>Redirect example</h2>
        <ul style="margin-left: 0; padding-left: 15px;">
            <li>
                <a href="exp://REPLACE_ME/">
                    Go back with no params
                </a>
            </li>
            <li>
                <a href="exp://REPLACE_ME/message=Hello%20World">
                    Pass back a message of "hello world"
                </a>
            </li>
            <li>
                <a href="exp://REPLACE_ME/authToken=23xbdbb21b3">
                    Pass back some fake auth token
                </a>
            </li>
        </ul>

        <p>
            Redirecting automatically back to app in
            <span class="countdown">5</span> seconds
        </p>
    </body>
</html>
`

**Comment by cruzach** [comment]
Hey @karanmartian, not sure if I understand your question. I don't think this is Expo-related, so I'm going to close, but will re-open if you can provide more info
