### ISSUE TITLE
`with-react-router` example arrives broken

### ISSUE THREAD

**Issue by lpender** [expo/examples#227]
**Steps to Reproduce**

1. `npx create-react-native-app`

2. Choose `with-react-router` as the app.

3. `yarn ios`

**Actual**  

Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `Link`, expected `function`.

![image](https://user-images.githubusercontent.com/1406554/95664527-9784d280-0afd-11eb-90a7-6cf4c038c148.png)

**Expected**

Should be without error

**Comment by brentvatne** [comment]
hi! we could use some help maintaining this template, because nobody on the expo team actually uses react router in this context. could you open a PR?

**Comment by EvanBacon** [comment]
I just tried this locally in the with-react-router example and it worked as expected on all platforms (SDK 43).

**Comment by goulashsoup** [comment]
@EvanBacon Pretty sure it is broken now, can you quickly recheck ?
