### ISSUE TITLE
`with-yarn-workspaces` fails to start apps due to `react-native-unimodules` symlink

### ISSUE THREAD

**Issue by kickbk** [expo/examples#242]
**Describe the bug**
`with-yarn-workspaces` demo fails to start apps due to `react-native-unimodules` symlink linking to itself

**To Reproduce**
Download and install `with-yarn-workspaces` with `yarn`. Start one of the apps with (for example) `yarn first-app`

**Expected behavior**
Supposed to start the app

@brentvatne, this happens since the latest update of `"expo-yarn-workspaces": "~1.3.0"`. I haven't dug into the code but I suspect expo-yarn-workspaces generates the `react-native-unimodules` symlink in each app directory, whether you declare it in `symlinks` inside `package.json` or not, which then loops back to itself, and fails with:

```
ENOENT: no such file or directory, stat '.../apps/first-app/node_modules/react-native-unimodules'
Error: ENOENT: no such file or directory, stat '../apps/first-app/node_modules/react-native-unimodules'
...
error Command failed with exit code 1.
```

Indeed when you `ls -ln` in the app directory, you can see the symlink
`lrwxr-xr-x  1 501  20   45 Jan 17 19:24 react-native-unimodules -> ../../../node_modules/react-native-unimodules`

**Comment by brentvatne** [comment]
thanks for the issue! this is fixed in `expo-yarn-workspaces@1.3.1` (thanks to this pr https://github.com/expo/expo/pull/11567) which i've now promoted to the latest tag on npm
