### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by huntr-helper** [expo/examples#271]
👋 Hello, we've received a report for a potential high severity security issue in your repository.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-expo/examples** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by byCedric** [comment]
@JamieSlome Is it possible to get the information from the security issue without authorizing Huntr to my Github account? Love to take a look, but I'm not feeling comfortable giving access through my GH account to parties I don't know.

**Comment by JamieSlome** [comment]
@byCedric - of course, will send over the details to the e-mail attached to your GitHub profile!
