### ISSUE TITLE
Text styles error - No overload matches this call

### ISSUE THREAD

**Issue by jung-youjin** [expo/examples#286]
**Describe the bug**

I am absolutely new to this area and I seek for community's help!

https://github.com/expo/examples/blob/a0e5bbfcde4720b6192bfb54b1546200b191030d/with-gatsby/src/pages/404.tsx#L11

I'm getting a `No overload matches this call` error on this line's `style` part with no code modification at all. I keep getting this red underline in my editor as the screenshot below. 😥

``` ts
No overload matches this call.
  Overload 1 of 2, '(props: TextProps | Readonly<TextProps>): Text', gave the following error.
    Type '{ fontWeight: "bold"; fontSize: string | number; }' is not assignable to type 'StyleProp<TextStyle>'.
      Types of property 'fontSize' are incompatible.
        Type 'string | number' is not assignable to type 'number'.
          Type 'string' is not assignable to type 'number'.
  Overload 2 of 2, '(props: TextProps, context: any): Text', gave the following error.
    Type '{ fontWeight: "bold"; fontSize: string | number; }' is not assignable to type 'StyleProp<TextStyle>'.
      Types of property 'fontSize' are incompatible.
        Type 'string | number' is not assignable to type 'number'.
          Type 'string' is not assignable to type 'number'.ts(2769)
index.d.ts(1047, 5): The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Text> & Readonly<TextProps> & Readonly<{ children?: ReactNode; }>'
index.d.ts(1047, 5): The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Text> & Readonly<TextProps> & Readonly<{ children?: ReactNode; }>'
(JSX attribute) style?: StyleProp<TextStyle>
@see — https://reactnative.dev/docs/text#style
```

Can anyone tell me which part or package that I'm missing? Thank you!

**To Reproduce**
-

**Expected behavior**
No red underline error

**Screenshots**
![image](https://user-images.githubusercontent.com/37402072/128950832-10d358cd-8655-4a61-85d7-e112b4b1bb3d.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
-

**Comment by EvanBacon** [comment]
The gatsby example is web only and cannot be run on native iOS clients.
