### ISSUE TITLE
ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by AnthonyLamot** [expo/examples#4]
I got the above error while trying this example: https://github.com/expo/examples/tree/master/with-webbrowser-redirect
It occured when trying to redirect from the browser to the app.

I used Android emulator (Nexus 6). 

Is this an error or am I missing something?

**Comment by cruzach** [comment]
I know this is a year later, (sorry about that), but that example was just updated and I tested and it works as it should

(If it still doesn't work on your end re-open and let me know 👍 )

Thanks
-Charlie
