### ISSUE TITLE
New Example: Expo Router with TypeScript

### ISSUE THREAD

**Issue by karlhorky** [expo/examples#412]
Hi there 👋 First of all, thanks for Expo and these examples, super useful!

I just wanted to request a new example with:

- Expo Router
- TypeScript (as fully-typed as possible)

The existing example [`with-router`](https://github.com/expo/examples/tree/master/with-router) uses JavaScript.

Potentially related:

- https://github.com/expo/router/discussions/272

**Comment by EvanBacon** [comment]
Simply run `touch tsconfig.json && npx expo` in the `with-router` template and it's fully TypeScript.

**Comment by karlhorky** [comment]
Ok, I will submit a PR for this then, so that these extra steps are not necessary.

**Comment by Josehower** [comment]
I created the PR https://github.com/expo/examples/pull/423

**Comment by yash-bansod-2003** [comment]
Simply run
 
`npx create-expo-app@latest --templete`

and then you get some options like

`
Blank,
 Blank (Typescript),
 Navigation (Typescript),
 Blank (Bare)
`

you need to choose **_Navigation (Typescript)_** for expo router with typescript.

**Comment by karlhorky** [comment]
@yash-bansod-2003 do these options include Expo Router too?

**Comment by alaksandarjesus** [comment]
**typo on template**

> npx create-expo-app@latest --templete

should be

> npx create-expo-app@latest --template
