### ISSUE TITLE
[with-sqlite] Snack example does not work

### ISSUE THREAD

**Issue by bliet** [expo/examples#92]
I cannot execute the example. See screenshot. 

![Screenshot_20190820_185650](https://user-images.githubusercontent.com/3314090/63367561-66d35e00-c37c-11e9-8e20-967da4986644.png)

KDE Neon (Ubuntu 18.04)
Chromium Version 76.0.3809.100

**Comment by neilrogers** [comment]
Any idea when this is going to be fixed or is there a work around? When I try the example locally i get the exact same error.

**Comment by mauriciord** [comment]
It's only in the browser, because of WebSQL :/

**Comment by bwalsh** [comment]
Sample problem here.
